language: python
sudo: false
addons:
  chrome: stable
matrix:
  include:
    - python: "2.7"
      env: PLONE_VERSION=5.0.x
    - python: "2.7"
      env: PLONE_VERSION=5.1.x
    - python: "2.7"
      env: PLONE_VERSION=5.2.x
    - python: "3.6"
      env: PLONE_VERSION=5.2.x
    - python: "3.7"
      env: PLONE_VERSION=5.2.x
      dist: xenial
      sudo: true
cache:
  pip: true
  directories:
  - eggs
  - downloads
before_install:
# install chrome webdriver
  - mkdir webdriver;
    wget https://github.com/mozilla/geckodriver/releases/download/v0.20.0/geckodriver-v0.20.0-linux64.tar.gz;
    tar -xzf geckodriver-v0.20.0-linux64.tar.gz -C webdriver;
    wget https://chromedriver.storage.googleapis.com/2.40/chromedriver_linux64.zip;
    unzip chromedriver_linux64.zip -d webdriver;
    export PATH=$PATH:$(pwd)/webdriver;
  - mkdir -p $HOME/buildout-cache/{eggs,downloads}
  - mkdir $HOME/.buildout
  - echo "[buildout]" > $HOME/.buildout/default.cfg
  - echo "download-cache = $HOME/buildout-cache/downloads" >> $HOME/.buildout/default.cfg
  - echo "eggs-directory = $HOME/buildout-cache/eggs" >> $HOME/.buildout/default.cfg
  - pip install zc.buildout
  - cp test-$PLONE_VERSION.cfg buildout.cfg
  - pip2.7 install popt || pip2.7 install --user  popt
install:
  - buildout -N annotate
  - buildout -N
  - pip install zest.pocompile
  - pocompile src
before_script:
  - 'export DISPLAY=:99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - sleep 3
script:
# Run code-analysis, except on Python 3.6, which mysteriously fails to find zc.buildout.
  - python --version 2> /dev/stdout | grep 3.6 || bin/code-analysis
  - bin/test --all $TEST_OPTIONS
  - grep  --include=output.xml -Rl  FAIL parts/test | xargs --no-run-if-empty -n 1 popt
  - bin/createcoverage -t '--all $TEST_OPTIONS'
  - grep  --include=output.xml -Rl  FAIL parts/test | xargs --no-run-if-empty -n 1 popt
after_success:
  - pip install -q coveralls
  - coveralls
